#!/usr/bin/env python3

"""
Create metadata file from an Ensembl GTF. Currently supports genes or transcripts as rows.
Default behavior creates gene-level metadata including gene_biotype from the attributes.
"""

__author__ = 'Rob Moccia'
__version__ = '0.1'

import gtf
import argparse
import sys
import csv

def configure_args(parser):
    parser.add_argument('--input', required=True, help='GTF file')
    parser.add_argument('--output', required=True, help='output file')
    parser.add_argument('--feature', choices=['gene', 'transcript'],
        default='gene', help='GTF feature to create metadata for')
    parser.add_argument('--attributes', action='append', default=['gene_biotype'],
        help='attributes to include as columns in output')
    parser.add_argument('--version', action='version',
        version='%(prog)s {version}'.format(version=__version__))

def process(args):

    num_records = 0
    num_written = 0

    attribute_header = [attribute for attribute in args.attributes]
    field_names = ['gene_id', 'gene_name', 'chr', 'start', 'end', 'strand'] + attribute_header
    if args.feature == 'transcript':
        field_names = ['transcript_id', 'transcript_name'] + field_names

    with open(args.output, 'w') as writer:
        csvwriter = csv.DictWriter(writer, fieldnames=field_names)
        csvwriter.writeheader()

        with open(args.input, 'r') as reader:
            for rec in gtf.open(reader, 'ensembl'):
                num_records += 1

                if rec.feature == args.feature:
                    attribute_dict = {attribute: rec.meta[attribute] for attribute in args.attributes}
                    # as of release 104, Ensembl is not using clone-based gene names anymore
                    # instead, the gene_id serves as a temporary stable ID until a gene name is
                    # generated by the relevant nomenclature committee
                    # https://www.ensembl.info/2021/03/15/retirement-of-clone-based-gene-names/
                    if 'gene_name' not in rec.meta.keys():
                        rec.meta['gene_name'] = rec.meta['gene_id']
                    base_row = {
                        'gene_id': rec.meta['gene_id'],
                        'gene_name': rec.meta['gene_name'],
                        'chr': rec.chr,
                        'start': rec.start,
                        'end': rec.stop,
                        'strand': rec.strand,
                        **attribute_dict
                        }
                    if args.feature == 'gene':
                        csvwriter.writerow(base_row)
                    elif args.feature == 'transcript':
                        csvwriter.writerow({
                            'transcript_id': rec.meta['transcript_id'],
                            'transcript_name': rec.meta['transcript_name'],
                            **base_row})
                    num_written += 1

    return dict(records=num_records, written=num_written)


if __name__ == '__main__':
    parser = argparse.ArgumentParser()
    configure_args(parser)
    res = process(parser.parse_args())
    print(res, file=sys.stderr)
